# Scaling features to a range
---

## Scaling features to lie within a given range

In [13]:
# import data
from sklearn.datasets import load_iris

In [14]:
X, y = load_iris(return_X_y=True)

In [15]:
X[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
mms = MinMaxScaler(feature_range=(0, 1))

In [18]:
X_mms = mms.fit_transform(X)
X_mms[:5]

array([[ 0.22222222,  0.625     ,  0.06779661,  0.04166667],
       [ 0.16666667,  0.41666667,  0.06779661,  0.04166667],
       [ 0.11111111,  0.5       ,  0.05084746,  0.04166667],
       [ 0.08333333,  0.45833333,  0.08474576,  0.04166667],
       [ 0.19444444,  0.66666667,  0.06779661,  0.04166667]])

After being scaled, the min feature value is 0 and the max feature value is 1.

In [11]:
X_mms.min(axis=0)

array([ 0.,  0.,  0.,  0.])

In [12]:
X_mms.max(axis=0)

array([ 1.,  1.,  1.,  1.])

## Maximumn absolute value of features to unit size 

In [19]:
from sklearn.preprocessing import MaxAbsScaler

In [20]:
mas = MaxAbsScaler()

In [26]:
import numpy as np
X = np.random.randn(10,2)

In [27]:
X

array([[ 1.16786131, -1.1925405 ],
       [ 0.46465578,  1.21548861],
       [ 1.5087463 ,  1.67468331],
       [ 0.11486724,  0.8906298 ],
       [-1.08016591,  0.16780035],
       [-1.51877613,  0.33970784],
       [ 0.38272549, -0.73337241],
       [ 2.01928944,  0.73962625],
       [-0.01943764,  1.18275869],
       [-0.01901672,  1.16926235]])

In [29]:
X_mas = mas.fit_transform(X)
X_mas

array([[ 0.5783526 , -0.71209912],
       [ 0.23010856,  0.72580207],
       [ 0.74716693,  1.        ],
       [ 0.05688498,  0.53181983],
       [-0.53492377,  0.10019826],
       [-0.75213394,  0.20284901],
       [ 0.18953473, -0.43791707],
       [ 1.        ,  0.44165141],
       [-0.00962598,  0.70625812],
       [-0.00941753,  0.69819908]])

In [30]:
abs(X_mas).min

array([[ 0.5783526 ,  0.71209912],
       [ 0.23010856,  0.72580207],
       [ 0.74716693,  1.        ],
       [ 0.05688498,  0.53181983],
       [ 0.53492377,  0.10019826],
       [ 0.75213394,  0.20284901],
       [ 0.18953473,  0.43791707],
       [ 1.        ,  0.44165141],
       [ 0.00962598,  0.70625812],
       [ 0.00941753,  0.69819908]])